[package]
name = "sonda-cli"
version = "0.1.0"
edition = "2021"
description = "CLI for Sonda waste classification tool"

[[bin]]
name = "sonda"
path = "src/main.rs"

[dependencies]
sonda-core = { path = "../sonda-core" }
clap = { version = "4", features = ["derive"] }
serde_json = "1"
